import type { Metadata } from "next";
import { AppWrapper } from "@/context/index";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "PDU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppWrapper>
        <body>
          {children}
          <Toaster />
        </body>
      </AppWrapper>
    </html>
  );
}
